#!/bin/bash

[ "$2" ] && WILL_FLOAT="$2"

SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

COMMAND="$EDITOR $SCRIPT_FILE"

if  [ $WILL_FLOAT ]; then
	if [[ -d $SCRIPT_FILE ]]; then
		FOLDER=$SCRIPT_FILE
		SCRIPT=$( ls "${FOLDER}" | rofi -dmenu -width 15 -lines 10 -p "${1}")
		[[ -z $SCRIPT ]] && exit
		SCRIPT_FILE="$SCRIPT_FOLDER/$1/$SCRIPT"
	fi

	COMMAND="$HOME/scripts/float-window i3-sensible-terminal $EDITOR $SCRIPT_FILE"
fi

if [[ -f $SCRIPT_FILE ]]; then
	exec $COMMAND
else
  echo '#!/bin/bash' > $SCRIPT_FILE
  chmod +x $SCRIPT_FILE
	exec $COMMAND
fi
