#!/bin/bash

killall -q nnn
killall -q gotop
killall -q pomotroid

while pgrep -u $UID -x nnn >/dev/null; do sleep 1; done
while pgrep -u $UID -x gotop >/dev/null; do sleep 1; done
while pgrep -u $UID -x pomotroid >/dev/null; do sleep 1; done

sleep 1;
exec i3-sensible-terminal --detach --name file_explorer -e nnn -R &
sleep 1; i3viswiz -c Spotify -f; i3-msg layout tabbed;

exec i3-sensible-terminal --detach -o font_size=10 -o window_margin_width=0 --name gotop -e gotop &
exec pomotroid &
exit
