#!/bin/bash

sleep 1;
killall -q nnn
killall -q gotop
killall -q pomotroid

while pgrep -u $UID -x nnn >/dev/null; do sleep 1; done
while pgrep -u $UID -x gotop >/dev/null; do sleep 1; done
while pgrep -u $UID -x pomotroid >/dev/null; do sleep 1; done

exec i3-sensible-terminal --detach --name file_explorer -e nnn -R &
exec i3-sensible-terminal --detach -o font_size=10 --name gotop -e gotop &
pomotroid &
i3viswiz -c Spotify -f; i3fyra -m A; i3-msg layout tabbed;
