#!/bin/bash

# Dependency: jump
# A small script to create a tmux session and open 3 windows
# window 1: my notes
# window 2: open project in neovim if a directory is given
# window 3: cd to same directory

SESSION="dev"
FOLDER="$HOME/Documents/repos/github.com/kirontoo"
SPLIT_PANES=false

function usage() {
cat <<USAGE

    Usage: $0 [-s session] [-r repo ] [--split]

    Options:
        -s, --session: tmux session name
        -r, --repo:    repo path
        --split:       information about argument
USAGE
    exit 1
}

function jump_dir() {
    # window should be a number
    local window = $1
    if [[ -n "$FOLDER" ]]; then
        tmux send-keys -t $SESSION:$WINDOW "cd ${FOLDER}" C-m
    fi
}

# if no arguments are provided, exit
if [ $# -eq 0 ]; then
    usage
    exit 1
fi

for arg in "$@"; do
    case $arg in
    -s | --session)
        SESSION=$2
        shift # remove arg (-s) name from `$@`
        shift # remove arg value (session) from `$@`
        ;;
    -r | --repo)
        FOLDER=$2
        ## Check if folder exists
        if [[ ! -d "$FOLDER" ]]; then
            echo "Directory does not exist: $FOLDER"
            exit 1
        fi
        shift
        shift
        ;;
    --split)
        ## split panes?
        SPLIT_PANES=true
        shift
        ;;
    -h | --help) 
        usage
        ;;
    esac
done

EXISTING_SESSION=$(tmux list-sessions | grep $SESSION)

# Only create new tmux session if it already doesn't exist
if [[ -z "$EXISTING_SESSION" ]]; then
    tmux new-session -d -s $SESSION

    # $SESSION:0 meaning session name : window number
    tmux rename-window -t $SESSION:0 'db'
    # tmux send-keys -t 'notes' 'nvim -c VimwikiIndex' C-m

    # Setup window for development
    tmux new-window -t $SESSION:1 -n 'dev'
    jump_dir 1

    tmux send-keys -t $SESSION:1 'nvim' C-m
    tmux send-keys -t $SESSION:1 Escape

    # Setup window for server
    tmux new-window -t $SESSION:2 -n 'server'
    jump_dir 2
else
    tmux attach -t $SESSION
fi

